[package]
name = "stepflow-main"
description = "Stepflow CLI."
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
publish = false

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
clap.workspace = true
error-stack.workspace = true
indexmap.workspace = true
rustyline.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml_ng.workspace = true
stepflow-analysis.workspace = true
stepflow-builtins.workspace = true
stepflow-components-mcp.workspace = true
stepflow-core.workspace = true
stepflow-execution.workspace = true
stepflow-mock.workspace = true
stepflow-plugin.workspace = true
stepflow-protocol.workspace = true
stepflow-server.workspace = true
stepflow-state.workspace = true
stepflow-state-sql.workspace = true
reqwest.workspace = true
walkdir.workspace = true
similar.workspace = true
nix.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-error.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
uuid.workspace = true
strum.workspace = true

[dev-dependencies]
clap-markdown = "0.1.4"
insta.workspace = true
insta-cmd.workspace = true
regex.workspace = true
tempfile.workspace = true

[[bin]]
name = "stepflow"
path = "src/main.rs"
