[project]
name = "stepflow"
version = "0.1.0"
description = "Stepflow shared types and interfaces"
readme = "README.md"
license = {text = "Apache-2.0"}
authors = [
    {name = "DataStax Inc."}
]
maintainers = [
    {name = "DataStax Inc."}
]
requires-python = ">=3.11"
keywords = [
    "workflow",
    "automation",
    "ai",
    "stepflow",
    "orchestration",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed"
]
dependencies = []

[project.urls]
Homepage = "https://stepflow-ai.github.io/stepflow/"
Documentation = "https://stepflow-ai.github.io/stepflow/"
Repository = "https://github.com/stepflow-ai/stepflow"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/stepflow"]
