[package]
name = "stepflow-cli"
description = "Stepflow CLI."
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
publish = false

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
clap.workspace = true
error-stack.workspace = true
rustyline.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml_ng.workspace = true
stepflow-analysis.workspace = true
stepflow-config.workspace = true
stepflow-core.workspace = true
stepflow-execution.workspace = true
stepflow-plugin.workspace = true
stepflow-server.workspace = true
stepflow-typecheck.workspace = true
reqwest.workspace = true
walkdir.workspace = true
similar.workspace = true
thiserror.workspace = true
tokio.workspace = true
log.workspace = true
stepflow-observability.workspace = true
url.workspace = true
uuid.workspace = true
strum.workspace = true
which.workspace = true

[dev-dependencies]
clap-markdown = "0.1.4"
insta.workspace = true
insta-cmd.workspace = true
regex.workspace = true
tempfile.workspace = true
testcontainers.workspace = true

[[bin]]
name = "stepflow"
path = "src/main.rs"
