[package]
name = "stepflow-server"
description = "Stepflow Server."
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
publish = false

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
axum.workspace = true
chrono.workspace = true
clap.workspace = true
error-stack.workspace = true
indexmap.workspace = true
serde_json.workspace = true
serde.workspace = true
serde_with.workspace = true
stepflow-analysis.workspace = true
stepflow-config.workspace = true
stepflow-core.workspace = true
stepflow-execution.workspace = true
stepflow-plugin.workspace = true
stepflow-state.workspace = true
thiserror.workspace = true
tokio.workspace = true
tower-http.workspace = true
tower.workspace = true
log.workspace = true
stepflow-observability.workspace = true
utoipa-axum.workspace = true
utoipa-swagger-ui.workspace = true
utoipa.workspace = true
uuid.workspace = true

[dev-dependencies]
stepflow-builtins.workspace = true
stepflow-mock.workspace = true
tower.workspace = true

[[bin]]
name = "stepflow-server"
path = "src/bin/main.rs"
