plugins:
  python:
    type: stepflow
    transport: stdio
    command: uv
    args: ["--project", "../../sdks/python/stepflow-server", "run", "stepflow_server"]
  builtin:
    type: builtin
routes:
  "/builtin/{*component}":
    - plugin: builtin
  "/python/{*component}":
    - plugin: python
