plugins:
  python:
    type: stepflow
    command: uv
    args: ["--project", "../../sdks/python", "run", "stepflow_py"]
  builtin:
    type: builtin
routes:
  "/builtin/{*component}":
    - plugin: builtin
  "/python/{*component}":
    - plugin: python
