[package]
name = "stepflow-builtins"
description = "Stepflow component plugin providing built-in components."
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[lib]
doctest = false

[dependencies]
chrono.workspace = true
dynosaur.workspace = true
error-stack.workspace = true
openai-api-rs.workspace = true
serde.workspace = true
utoipa.workspace = true
serde_json.workspace = true
serde_yaml_ng.workspace = true
stepflow-plugin.workspace = true
stepflow-core.workspace = true
stepflow-state.workspace = true
thiserror.workspace = true
tokio.workspace = true
log.workspace = true
trait-variant.workspace = true
uuid.workspace = true

[dev-dependencies]
test-with.workspace = true
tempfile.workspace = true
