[package]
name = "stepflow-execution"
description = "Execution logic for workflows."
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[lib]
doctest = false

[dependencies]
bit-set.workspace = true
chrono.workspace = true
error-stack.workspace = true
futures.workspace = true
log.workspace = true
nonempty.workspace = true
serde.workspace = true
serde_json.workspace = true
stepflow-analysis.workspace = true
stepflow-observability.workspace = true
stepflow-plugin.workspace = true
stepflow-core.workspace = true
stepflow-dtos.workspace = true
stepflow-state.workspace = true
thiserror.workspace = true
tokio.workspace = true
uuid.workspace = true

[dev-dependencies]
stepflow-mock.workspace = true
