[package]
name = "stepflow-protocol"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false
description = "Types defining the stepflow JSON-RPC protocol."

[lib]
doctest = false

[dependencies]
async-stream.workspace = true
erased-serde.workspace = true
error-stack.workspace = true
fastrace.workspace = true
futures.workspace = true
indexmap.workspace = true
reqwest.workspace = true
reqwest-eventsource.workspace = true
serde_json.workspace = true
serde.workspace = true
stepflow-core.workspace = true
stepflow-dtos.workspace = true
stepflow-execution.workspace = true
stepflow-plugin.workspace = true
stepflow-state.workspace = true
subst.workspace = true
utoipa.workspace = true
strum.workspace = true
thiserror.workspace = true
tokio.workspace = true
log.workspace = true
uuid.workspace = true
which.workspace = true

[target.'cfg(unix)'.dependencies]
nix.workspace = true

[dev-dependencies]
similar-asserts.workspace = true
serde_json.workspace = true

[lints]
workspace = true

[package.metadata.cargo-machete]
ignored = ["reqwest-eventsource"]
