[package]
name = "stepflow-protocol"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false
description = "Types defining the stepflow JSON-RPC protocol."

[lib]
doctest = false

[dependencies]
erased-serde.workspace = true
error-stack.workspace = true
futures.workspace = true
indexmap.workspace = true
reqwest.workspace = true
reqwest-eventsource.workspace = true
schemars.workspace = true
serde_json.workspace = true
serde.workspace = true
stepflow-core.workspace = true
stepflow-plugin.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tracing.workspace = true
uuid.workspace = true
which.workspace = true

[dev-dependencies]
similar-asserts.workspace = true
stepflow-state.workspace = true
serde_json.workspace = true

[lints]
workspace = true
