plugins:
  python:
    type: stepflow
    command: uv
    args: ["--project", "../../sdks/python", "run", "stepflow_worker"]
  builtin:
    type: builtin
routes:
  "/python/{*component}":
    - plugin: python
  "/{*component}":
    - plugin: builtin
