[package]
name = "stepflow-mock"
description = "Mock component plugin for testing purposes."
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[lib]
doctest = false

[dependencies]
error-stack.workspace = true
serde.workspace = true
stepflow-plugin.workspace = true
stepflow-core.workspace = true
log.workspace = true
tokio.workspace = true
utoipa.workspace = true

[dev-dependencies]
static_assertions.workspace = true