[package]
name = "stepflow-state-etcd"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lib]
doctest = false

[dependencies]
chrono = { workspace = true }
error-stack = { workspace = true }
etcd-client = "0.18"
futures = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
stepflow-state = { workspace = true }
tokio = { workspace = true }
utoipa = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
etcd-client = "0.18"
stepflow-state = { workspace = true }
testcontainers = { workspace = true }
tokio = { workspace = true, features = ["test-util"] }
uuid = { workspace = true }
